[package]
name = "zoeae"
version = "0.0.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["image", "markdown", "highlighter", "tokio"] }
rfd = "0.17.1"
tokio = { version ="1.49.0", features = ["fs"] }
uuid = { version = "1.19.0", features = ["v4"] }
webbrowser = "1.1.0"
